### ISSUE TITLE
cupy import crash

### ISSUE THREAD

**Issue by ZacDiggum** [tueimage/gryds#2]
Hi there,

after having installed cupy gryds won't import anymore. I have a Windows 10 machine with  Python 3.6, Cuda 10.0, cupy-cuda100 and gryds.
Here is the error message:

Traceback (most recent call last):
  File "gryds_test.py", line 2, in <module>
    import gryds
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\winpython\python\lib\site-packages\gryds-0.0.1-py3.6.egg\gryds\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\winpython\python\lib\site-packages\gryds-0.0.1-py3.6.egg\gryds\interpolators\__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\winpython\python\lib\site-packages\gryds-0.0.1-py3.6.egg\gryds\interpolators\cuda.py", line 9, in <module>
  File "C:\winpython\python\lib\site-packages\cupyx\__init__.py", line 2, in <module>
    from cupyx.rsqrt import rsqrt  # NOQA
  File "C:\winpython\python\lib\site-packages\cupyx\rsqrt.py", line 1, in <module>
    from cupy.core.core import create_ufunc
  File "C:\winpython\python\lib\site-packages\cupy\__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "C:\winpython\python\lib\site-packages\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy\core\carray.pxi", line 50, in init cupy.core.core
AttributeError: type object 'cupy.core.core.Indexer' has no attribute '__reduce_cython__'

Any recommendations on how to make it work?

[errlog.txt](https://github.com/tueimage/gryds/files/3489066/errlog.txt)

**Comment by ZacDiggum** [comment]
Sorry, there was a cupy installation problem. Seems to work now!
